In this lab we will explore the convergence of iterative methods for linear systems.

# Exercise 1: Convergent iteration



In class we are going to study methods to solve $Ax = b$ that involve splitting $A$ as follows: $A = S - T$. Here let's choose $S=I$ and $T = I-A$. Then the solution to $Ax = b$ is the fixed point of $g(x) = Tx + b$. 

### Question 

Show this (on a sheet of paper). 



### Question 

Choose an initial guess $x^{(0)}$. Use fixed-point iteration to obtain an approximate solution to $Ax = b$, where $A$ and $b$ are: 




In [1]:
import numpy as np 
A = np.array([[1, .2, .3],
              [-.1, 1.1, .3],
              [.2, .5, 1]])
b = np.array([[1],
              [1],
              [1]])

### Solution

In [2]:
def fixed_point_iteration(x0=np.array([[0],
                                       [0],
                                       [0]]), 
                          number_iterations=20):  
    T = np.eye(3) - A
    x = x0 
    # your code here 
    
    print 
    print '|Ax - b|: ' 
    print np.linalg.norm(np.dot(A,x) - b)

fixed_point_iteration()


|Ax - b|: 
1.73205080757


# Exercise 2: Divergent iteration

Now consider



In [3]:
A = np.array([[1, 2.2, 0.],
              [-3.1, 1.1, 0.],
              [0., 0., .8]])
b = np.array([[0.],
              [0.],
              [1]])

### Question

Use `fixed_point_iteration` (together with its default parameters) to solve $Ax = b$. 

### Solution

In [4]:
fixed_point_iteration()


|Ax - b|: 
1.0


### Question 

Compute by hand (i.e. on a sheet of paper) $x_0$, $x_1$, $x_2$ and $x_3$. Can you explain why this method converges? 


### Solution

As you did the hand calculations, you should have noticed that 

$$ x_k = 
\left[
\begin{array}{c} 
0 \\ 
0 \\ 
\sum_{n=0}^k (0.2)^n
\end{array} 
\right]
$$

which tends to $\ldots$


### Question 

Show that the method does not converge with initial guess $x^{(0)} = [1,0,0]$. 

### Solution

The reason behind the divergence of $x$ has to do with the eigenvalues of $T$. 

### Question 

Use `LA.eigvals` from the numpy library to find the eigenvalues of $T$. 

### Solution

In [11]:
from numpy import linalg as LA
I = np.eye(3)
T = None # your code here 
print 'eigenvalues of T:', # your code here

eigenvalues of T:


In this case two are complex (Python uses `j` to represent the imaginary number $\sqrt{-1}$) and one is real. Clearly, the largest eigenvalue of $T$ has magnitude greater than unity, i.e. $\rho(T) > 1$. It turns out that $T$-matrices with $\rho(T) < 1$ always converge but no guarantee can be made when $\rho(T) > 1$. No surprise then that we could find starting values of $x$ that lead to a divergent sequence $\{x_k\}$. 

# Exercise 3: Fixing a divergent iteration scheme

Now consider the matrix $A$ and the column vector $b$: 



In [7]:
A = np.array([[1, .2, 0.],
              [-.3, 4, 1.],
              [0., 1., 8]])
b = np.array([[1],
              [1],
              [1]])

### Question 

Use `fixed_point_iteration` to show that fixed-point iteration does not converge. 

### Solution





### [Preconditioning](https://en.wikipedia.org/wiki/Preconditioner)

Solving $Ax = b$ is equivalent to solving $PAx = Pb$. Suppose however that $PA \approx I$. Then $T = I - PA \approx 0$. We therefore expect that the eigenvalues of $T$ are distributed around zero. This is great news because it opens up the possibility that the spectral radius of $T$ is smaller than unity, in which case fixed-point iteration should converge. 

One strategy for coming up with $P$ is to scale each row of $A$ by its diagonal element. This makes each diagonal element equal to unity, as in the identity matrix. Moreover, if the off-diagonal elements of $A$ in any given row are smaller than the diagonal element in that row, then the off-diagonal elements of the scaled matrix are expected to be smaller than unity, hopefully much smaller, just as they are in the identity matrix. This is expected to be a particularly common occurrence if the original matrix is sparse. 

One way to scale each row by its diagonal element is to construct a diagonal matrix $D$ containing the diagonal elements of $A$ and compute $D^{-1}A$: 

In [12]:
D = np.diagflat(np.diag(A))
print 'D: '
print D 

I_approx = np.dot(np.linalg.inv(D), A)
print 'I_approx: '
print I_approx

print 'eigenvalues of T = I - A:', LA.eigvals(I - A)
print 'eigenvalues of T = I - I_approx:', LA.eigvals(I - I_approx)

D: 
[[ 1.  0.  0.]
 [ 0.  4.  0.]
 [ 0.  0.  8.]]
I_approx: 
[[ 1.     0.2    0.   ]
 [-0.075  1.     0.25 ]
 [ 0.     0.125  1.   ]]
eigenvalues of T = I - A: [-0.02115992 -2.74320906 -7.23563102]
eigenvalues of T = I - I_approx: [ -1.27475488e-01   2.51534904e-17   1.27475488e-01]


Notice that in the original system $Ax = b$, we have $\rho(T) > 1$, whereas in the preconditioned system $D^{-1}A = D^{-1}b$, we have $\rho(T) < 1$. 

### Question

Use fixed-point iteration to solve the pre-conditioned system. 

### Solution 

In [13]:
# your code here 

print 
print '|Ax - b|: ' 
print # your code here


|Ax - b|: 

