We will consider forward substitution and an iteration scheme for linear systems.

# Exercise 1: Forward substitution

Let $L$ be an $n\times n$ lower triangular matrix with non-zero diagonal entries. We want to solve

$$ Lx = b.$$

More explicitly:

$$\left[\begin{array}{cccccccc} l_{11} & 0 & 0 &0 & \cdots & 0 \\ l_{21} & l_{22} & 0 & 0 & \cdots & 0 \\ l_{31} & l_{32} & l_{33} & 0 & \cdots & 0 \\ \vdots & &&&& \vdots \\ l_{n1} & l_{n2} & \cdots && \cdots & l_{nn}\end{array}\right] \left[ \begin{array}{c} x_1 \\ x_2 \\ \vdots \\ \vdots \\ x_n \end{array} \right] = \left[ \begin{array}{c} b_1 \\ b_2 \\ \vdots \\ \vdots \\ b_n \end{array} \right].$$

This gives the set of equations

$$ \begin{array}{l} x_1 = b_1/l_{11}\\ x_2 = (b_2 - l_{21} x_1)/l_{22}\\ x_3 = (b_3 - l_{31} x_1 - l_{32} x_2)/l_{33}\\ \vdots \end{array} $$

And in general

$$ x_i = \left( b_i - \sum_{j=1}^{i-1} l_{ij} x_j \right)/l_{ii}. $$

### Question
Write a function that implements the above algorithm.

### Solution

In [1]:
import numpy as np 

def forward_substitution(L, b):
    # your code here 
    pass

### Question 

Test your algorithm on the following matrices. [Hint: you'll probably need `numpy.linalg.inv`]

In [2]:
n = 10
L = np.random.rand(n,n)
b = np.random.rand(n,1)

for i in range(n):
    for j in range(i+1,n):
        L[i,j] = 0.0
print L

[[ 0.12218855  0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.84276927  0.27499014  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.02014084  0.90003024  0.51712309  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.99577424  0.74580207  0.24735478  0.84504589  0.          0.          0.
   0.          0.          0.        ]
 [ 0.0694568   0.31150159  0.01004078  0.74624155  0.79771804  0.          0.
   0.          0.          0.        ]
 [ 0.30511818  0.28809813  0.0547089   0.3254238   0.53463079  0.625366    0.
   0.          0.          0.        ]
 [ 0.53246696  0.3257752   0.83516626  0.13914769  0.28298432  0.46565792
   0.71786591  0.          0.          0.        ]
 [ 0.73985626  0.74734355  0.59502587  0.43735031  0.58292222  0.34973916
   0.68648961  0.16769072  0.          0.        ]
 [ 0.97892209  0.83261096  0.73011881  0.7282898

### Solution

In [1]:
# your code here

# Exercise 2: An iterative approach

Create a matrix $A$:

In [4]:
n = 4
shape = (n,n)
A = np.zeros(shape)
for i in range(n):
    for j in range(n):
        dif = i-j
        if i >= j: 
            A[i,j] = (-1)**dif*(dif+1)
        else:
            A[i,j] = (0.1)**(-dif)
print A

[[  1.00000000e+00   1.00000000e-01   1.00000000e-02   1.00000000e-03]
 [ -2.00000000e+00   1.00000000e+00   1.00000000e-01   1.00000000e-02]
 [  3.00000000e+00  -2.00000000e+00   1.00000000e+00   1.00000000e-01]
 [ -4.00000000e+00   3.00000000e+00  -2.00000000e+00   1.00000000e+00]]


Let $U$ be a matrix that coincides with $A$ above the diagonal, but is zero on the diagonal and below:


In [5]:
U = A.copy() # not U = A
for i in range(n):
    for j in range(n):
        if i >= j: 
            U[i,j] = 0.0
print U 

[[ 0.     0.1    0.01   0.001]
 [ 0.     0.     0.1    0.01 ]
 [ 0.     0.     0.     0.1  ]
 [ 0.     0.     0.     0.   ]]


Similarly, let $L$ be a matrix that differs from $A$ only above the diagonal, where $L$ is zero:  

In [6]:
L = A.copy() # not L = A
for i in range(n):
    for j in range(n):
        if i < j: 
            L[i,j] = 0.0
print L 

[[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 3. -2.  1.  0.]
 [-4.  3. -2.  1.]]


Then solving $Ax = b$ is equivalent to solving 

\begin{equation} 
Lx = b - Ux.
\end{equation} 

Though the LHS is of the form of an equation amenable to forward substitution, the RHS is not: it depends on $x$ (instead of being constant). The key point is that the solution of $Lx = b - Ux$ can be viewed as the fixed point of the function 

\begin{equation} 
g(x) = L^{-1} (b - Ux).
\end{equation} 



### Question 

How can the fixed-point method be combined with back-substitution to solve for $x$?



### Solution 
Write your solution on a sheet of paper.


### Question 

Implement your iterative algorithm in Python for a vector $b$ consisting entirely of ones and a starting $x$-value of all zeros. Test the solution so obtained.

### Solution

In [2]:
# your code here 