In [1]:
# Student name: 
# Student ID: 

# Math105A homework

Please do the following (non-graded) homework taken from the Text in preparation for the midterm exam:

**Pivoting strategies**: Section 6.2: 1b, 5b, 31

**Matrix inversion and Determinants**:
* Section 6.3: 1d, 2c, 5b, 9c
* Section 6.4: 1b, 6, 8, 10

**(P)LU factorization**: Section 6.5: 4a-b, 5a, 6a

# Math105LA computer assignment

Please fill the remainder of this notebook with your code (remove `pass` after `# your code here`, if present), execute all cells, save the notebook on your machine, and upload the notebook to the [Math105LA Assign04 Dropbox](https://eee.uci.edu/toolbox/dropbox/) by the deadline indicated in the Dropbox. A primer on Dropbox is [here](https://eee.uci.edu/help/dropbox/instructors/_assets/dropbox_primer.pdf).

# Problem 1

Implement both a Gaussian elimination function `gaussian_elimination` and a backward substitution function `back_substitution`.

In [2]:
# Biao Yang's solution

def gaussian_elimination(A):

    # INPUT: augmented_matrix, an n x (n+1) numpy matrix 

    # OUTPUT: augmented_matrix, altered to be an n x (n+1) upper-triangular matrix, 
    # or an error message if the method failed 
    # (because of rank deficiency)
    
    # see pseudocode in Lecture10
    # see Algo 6.1 on p364 of Text 
    sz = A.shape
    n = sz[0]
    U = A.copy()
    tol = 10**(-10)
    for i in range(0,n-1):
        for p in range(i,n):
            if abs(U[p,i]) > tol:
                break
        if abs(U[p,i]) < tol:
            return 'Method failed: matrix is rank deficient1'
        if p != i:
            U[[i,p],:] = U[[p,i],:]
        for j in range(i+1,n):
            m = U[j,i] / float(U[i,i])
            U[j,:] -=  m*U[i,:]
    if abs(U[n-1,n-1]) < tol:
        return 'Method failed: matrix is rank deficient2'
    return U
        
def back_substitution(U):

    # INPUT: U, an n x (n+1) numpy upper-triangular matrix with non-zero diagonal entries

    # OUTPUT: x, the solution to U[:,:n] x = U[:,-1]

    # print an error message if the method failed 
    # (because of rank deficiency)
    
    # see pseudocode in Lecture10
    # see Algo 6.1 on p364 of Text 
    sz = U.shape
    n = sz[0]
    x = zeros((n,1))
    x[n-1]=U[n-1,n] / float(U[n-1,n-1])
    for i in range(n-2,-1,-1):
        x[i]=U[i,n]-dot(U[i,i+1:n],x[i+1:n])
        x[i]=x[i]/float(U[i,i])
    return x      

# Problem 2

Demonstrate that your code works by using it to solve $A x = b$ when $A$ is invertible (i.e. non-singular). Also give your code a non-invertible matrix and show that your code gives an error message. Use different-dimensional linear systems containing random coefficients.


In [3]:
# Biao Yang's solution

from numpy import *
print 'Example 1:\n'
A = array([[1.0,1,1,3],[2,-1,2,6],[-1,1,1,1]])
print 'Matrix:\n',A
B = gaussian_elimination(A)
print 'After Gaussian Elimination:\n',B
x = back_substitution(B)
print 'Solving for x:\n',x
print 'Checking max(abs(Ax-b):\n'
print max(abs(dot(A[0:3,0:3],x)-A[0:3,3].reshape(3,1)))

print 'Example 2:\n'
D = random.rand(4, 5)
print 'Matrix:\n',D
E = gaussian_elimination(D)
print 'After Gaussian Elimination:\n',E
y = back_substitution(E)
print 'Solving for x:\n',y
print 'Checking max(abs(Ax-b):\n'
print max(abs(dot(D[0:4,0:4],y)-D[0:4,4].reshape(4,1)))

print 'Example 3:\n'
F = array([[1.0,2,3,4],[2,2,4,6],[1,2,3,5]])
print 'Matrix:\n',F
G = gaussian_elimination(F)
print 'After Gaussian Elimination:\n',G

Example 1:

Matrix:
[[ 1.  1.  1.  3.]
 [ 2. -1.  2.  6.]
 [-1.  1.  1.  1.]]
After Gaussian Elimination:
[[ 1.  1.  1.  3.]
 [ 0. -3.  0.  0.]
 [ 0.  0.  2.  4.]]
Solving for x:
[[ 1.]
 [-0.]
 [ 2.]]
Checking max(abs(Ax-b):

[ 0.]
Example 2:

Matrix:
[[ 0.85330847  0.81358296  0.09994317  0.86797184  0.83932437]
 [ 0.04928582  0.03827487  0.835185    0.61374932  0.420431  ]
 [ 0.2584681   0.17696733  0.57669748  0.36973217  0.38129971]
 [ 0.10988916  0.74246386  0.31785075  0.82003972  0.95597209]]
After Gaussian Elimination:
[[ 0.85330847  0.81358296  0.09994317  0.86797184  0.83932437]
 [ 0.         -0.00871646  0.82941244  0.56361657  0.37195288]
 [ 0.          0.         -6.06377388 -4.38505295 -2.83729901]
 [ 0.          0.          0.         -2.15903155 -0.47541382]]
Solving for x:
[[-0.17030632]
 [ 0.93742508]
 [ 0.30867252]
 [ 0.22019772]]
Checking max(abs(Ax-b):

[  3.66373598e-15]
Example 3:

Matrix:
[[ 1.  2.  3.  4.]
 [ 2.  2.  4.  6.]
 [ 1.  2.  3.  5.]]
After Gaussian E