In [1]:
# Student name: 
# Student ID: 

# Math105A homework

Please do the following (non-graded) homework taken from the Text in preparation for a (graded) quiz on Thursday. 

Section 7.1: 1b, 2, 8

Section 7.2: 1a-c, 6, 9

# Math105LA computer assignment

Please fill the remainder of this notebook with your code (remove `pass` after '`#your code here`'), execute all cells, save the notebook on your machine, and upload the notebook to the [Math105LA Assign05 Dropbox](https://eee.uci.edu/toolbox/dropbox/) by the deadline indicated in the Dropbox. A primer on Dropbox is [here](https://eee.uci.edu/help/dropbox/instructors/_assets/dropbox_primer.pdf).

### PLU factorization

The following pseudo-code implements PLU factorization with partial pivoting:

```
INPUT: An n x n matrix A

OUTPUT: An n x n permutation matrix P, an n x n lower-triangular matrix
L and an n x n upper-triangular matrix U such that PA = LU

STEP 1: Set P = I, L = I
STEP 2: For j = 1,2,.. n-1 do:
  STEP 3: Set MAX to be the maximum of abs(A(i,j)) for i =
  j,j+1,..,n
  STEP 4: If MAX = 0 then
    DISPLAY('Method failed: matrix is rank deficient')
    OUTPUT(A);
    STOP.
  STEP 5: Let p be the smallest number such that MAX = abs(A(p,j));
  STEP 6: Do Rj <--> Rp on A;
  STEP 7: Do Cj <--> Cp on L;
  STEP 8: Do Rj <--> Rp on L;
  STEP 9: Do Rj <--> Rp on P;
  STEP 10: For i = j+1,j+2,...,n do STEPS 11-12
    STEP 11: Set L(i,j) = A(i,j)/A(j,j)
    STEP 12: Do Ri - L(i,j) Rj --> Ri on A
STEP 13: OUTPUT([P,L,A]); STOP.
```

### Problem 1 (ungraded)

Apply this algorithm to the example worked out on pp12-14 inclusive of [Lecture 14](https://github.com/petermchale/math105A/blob/master/lectures/Lecture14.pdf). Notice how the algorithm computes $L$ on the fly by interchanging rows **and** columns as elimination proceeds. Contrast that with my much slower approach in which I have to pass through the elimination process twice to figure out $L$. Clever! 

### Problem 2

Use the pseudo-code to implement PLU factorization with partial pivoting in Python.

In [1]:
def number_rows(A):     
    n, m = A.shape     
    return n

def is_zero(x, epsilon=1e-10):    
    return abs(x) < epsilon

def swap_row(A, i, j):  
    A[[i,j],:] = A[[j,i],:]
    
def swap_col(A, i, j):  
    A[:,[i,j]] = A[:,[j,i]]

def PLU(A):
    A = np.array(A, dtype=np.float32)    
    n = number_rows(A)
    P = np.eye(n, dtype=np.float32)
    L = np.eye(n, dtype=np.float32)
    U = A.copy() 
    # your code here 
    return P,L,U

### Problem 3

Demonstrate that your code works by computing `norm(P*A-L*U)` on the following matrix, $A$.  What value do you expect if your implementation is correct?

In [2]:
import numpy as np
A = np.array([[0,0,-1,1],
              [1,1,-1,2],
              [-1,-1,2,0],
              [1,2,0,2]])
print 'A:'
print A
P,L,U = PLU(A)
print 'P: '
print P 
print 'L:'
print L 
print 'U:'
print U 
print 'norm(P*A-L*U) = ', np.linalg.norm(np.dot(L,U)-np.dot(P,A))

A:
[[ 0  0 -1  1]
 [ 1  1 -1  2]
 [-1 -1  2  0]
 [ 1  2  0  2]]
P: 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
L:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
U:
[[ 0.  0. -1.  1.]
 [ 1.  1. -1.  2.]
 [-1. -1.  2.  0.]
 [ 1.  2.  0.  2.]]
norm(P*A-L*U) =  0.0
