In [1]:
# Student name: 
# Student ID:

This Lab Project should be completed ON YOUR OWN. You may discuss the problems with your classmates but the final version must be your own work. We will not hesitate to give zero points for an assignment if it is not your own work.

Upload the notebook to the [Math105LA Assign_LabProject Dropbox](https://eee.uci.edu/toolbox/dropbox/) by the deadline indicated in the Dropbox. No late submissions will be accepted.

# Relaxation for fixed-point iteration

We may find the fixed-point of the function

$$g(x) = \cos^2(x),$$

using the following iteration,

$$ x_{k+1} = g_w(x_k) = wg(x_k) + (1-w)x_k,$$

obtained by averaging the current iterate, $x_k$, and the value the next iterate would have  in ordinary fixed-point iteration, $g(x_k)$.

If $p$ is the fixed point, we'd like to choose $w$ so that $g'_w(p) = 0$ so that we get quadratic convergence, but $p$ is not known. One way to deal with this is to choose $w$ such that 
$g_w'(x_{k}) = 0$ before computing $x_{k+1}$ (the relaxation parameter $w$ does not need to be the same at each iteration). 

### Problem 

Implement this method to compute the fixed point of $g(x)$. Show either numerically or analytically that this method converges quadratically.

### Solution

In [1]:
# your code here 

# The inverse power method

Assume the eigenvalues of an $n \times n$ matrix $A$ satisfy

$$|\lambda_1| \geq |\lambda_2| \geq \cdots \geq |\lambda_{n-1}| > |\lambda_n| > 0.$$

The [inverse power method](https://en.wikipedia.org/wiki/Inverse_iteration) can be used to compute $\lambda_n$, the smallest eigenvalue of $A$ in modulus. The basic idea is to use the standard power method to compute the largest eigenvalue of $A^{-1}$, which turns out to be the reciprocal of the smallest eigenvalue of $A$. 

### Problem 

Write a function
`InvPower(A,Nmax,TOL)`
that performs the following:

* Compute a $PA=LU$ factorization of $A$ using partial pivoting.

* Choose a vector $x^{(0)}$, with unit length.

* For $k = 1,2,\ldots,Nmax$ do 
    * Compute $y^{(k)} = A^{-1} x^{(k-1)}$ using the $PA=LU$ factorization, forward and backward substitution. 

    * Set $\lambda^{(k)} = [(y^{(k)})^Tx^{(k-1)}]^{-1}$.

    * Set $x^{(k)} = y^{(k)}/\|y\|_2$.

    * If $|\lambda^{(k)} - \lambda^{(k-1)}| < TOL$ then return $\lambda^{(k)}$.
    
    
* If $k = Nmax$ return an appropriate error message.

### Solution


In [2]:
# your code here

### Problem 

Use your function to compute the smallest (in modulus) eigenvalue of the following matrix. Report the number of iterations to convergence. Compute the same eigenvalue using the numpy library and check that it agrees with your answer. 

In [9]:
A = np.array([[-2,1,0,0,0],
              [1,-2,1,0,0],
              [0,1,-2,1,0],
              [0,0,1,-2,1],
              [0,0,0,1,-2]], dtype=float)
print A

[[-2.  1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  1. -2.]]


### Solution

In [3]:
# your code here